# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('option_num', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor.Option', verbose_name='record option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor.Question', verbose_name='record question')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor.Academy', verbose_name='teacher academy')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stu_no', models.CharField(max_length=20)),
                ('id_no', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=10)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor.Academy', verbose_name='user academy')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor.User', verbose_name='record user'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor.Question', verbose_name='question id'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user', 'question', 'option'], name='counselor_r_user_id_5e8042_idx'),
        ),
    ]
